feat(usuario):HU008 Afiliacion plan gratuito
MateoBohorquezUniandes/MISW4501-2024-11-14-Proyecto-Final pull request #26
Opened 2024-04-06 16:51 UTC by Helena-Pat29

## Historias de Usuario/Arquitectura Relacionadas

* [HU008](https://dev.azure.com/misoliticos/SportApp/_backlogs/backlog/SportApp%20Team/Stories?showParents=false&System.Tags=Funcional&System.IterationPath=SportApp%5CCiclo%202%20Sprint%201%2CSportApp%5CCiclo%202%20Sprint%203&workitem=111):  Afiliación al Plan Gratuito

## Changelog

> Describa de forma precisa los cambios realizados en el Pull Request. Ejemplo:
* Se crea agrega el atributo Plan de Afiliacion al Deportista

## Checklist

> Antes de solicitar reviews, los siguientes elementos deben estar listos

### Generales

- [x] La rama de origen sigue la convención mencionada en `.github/CONTRIBUTING`
- [x] Pull Request cuenta con un título apropiado
- [x] Se ha seleccionado el Milestone correspondiente
- [x] Se han colocado los labels para (microservicio, estado, tipo)

### CI/CD

- [x] Se modificaron o agregaron pruebas al backlog
- [x] Los cambios cuentan con la cobertura mínima de pruebas (70%)
- [x] Se actualizaron las colecciones de Postman
- [x] Todos los checks del repositorio han sido exitosos

2024-04-07 07:35 UTC, s-cortes requested changes

2024-04-07 07:35 UTC, s-cortes commented on .vs/MISW4501-2024-11-14-Proyecto-Final/FileContentIndex/a54c5d93-a360-493f-91f5-5957f6c6415d.vsidx
No incluir

2024-04-07 07:35 UTC, s-cortes commented on .vs/MISW4501-2024-11-14-Proyecto-Final/FileContentIndex/read.lock
No incluir

2024-04-07 07:35 UTC, s-cortes commented on .vs/MISW4501-2024-11-14-Proyecto-Final/v17/.suo
No incluir

2024-04-07 07:35 UTC, s-cortes commented on .vs/ProjectSettings.json
No incluir

2024-04-07 07:35 UTC, s-cortes commented on .vs/VSWorkspaceState.json
No incluir

2024-04-07 07:35 UTC, s-cortes commented on .vs/slnx.sqlite
No incluir

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/application/dtos.py
> +    planAfiliacion: str = field(default_factory=str)
```suggestion
    plan_afiliacion: str = field(default_factory=str)
```

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/domain/entities.py
> +    planAfiliacion: str = field(default_factory=str)
```suggestion
    plan_afiliacion: str = field(default_factory=str)
```

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/domain/exceptions.py
> +        super().__init__(message, code="login.credentials")
```suggestion
        super().__init__(message, code="login.credentials")

```

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/domain/rules.py
> +class ValidPlanAfiliacion(BusinessRule):
```suggestion
class _ValidPlanAfiliacion(BusinessRule):
```

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/domain/rules.py
> +class ValidPlanAfiliacion(BusinessRule):
Falta agregarlo a las validaciones del `Deportista`

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/domain/value_objects.py
> +#Agregando Plan de Afiliacion
innecesario el comentario

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/infrastructure/dtos.py
> +
```suggestion

```

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/infrastructure/dtos.py
> +    #usuario_id = db.Column(db.String(10), ForeignKey("usuario.identificacion"), primary_key=True)
innecesario, borrar

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/infrastructure/dtos.py
> +       # "inherit_condition": (usuario_id == Usuario.identificacion),
innecesario, borrar comentario

2024-04-07 07:35 UTC, s-cortes commented on src/usuarios/tests/test_api.py
> +            "planAfiliacion":"GRATUITO",
No se debe agregar en el JSON

2024-04-09 08:12 UTC, s-cortes approved these changes

2024-04-09 23:45 UTC, MateoBohorquezUniandes approved these changes
Aprobado ultimo commit

2024-04-09 23:46 UTC, merged