Feat/planesHU029 Listar planes asociados
MateoBohorquezUniandes/MISW4501-2024-11-14-Proyecto-Final pull request #32
Opened 2024-04-11 17:19 UTC by Helena-Pat29

## Historias de Usuario/Arquitectura Relacionadas

> Coloque la URL y título de las historias relacionadas al Pull Request. Ejemplo:
* [HU029](https://dev.azure.com/misoliticos/SportApp/_backlogs/backlog/SportApp%20Team/Stories?showParents=false&System.Tags=Funcional&System.IterationPath=SportApp%5CCiclo%202%20Sprint%202&System.State=Active%2CClosed%2CNew&System.AssignedTo=h.patarroyo%40uniandes.edu.co&workitem=162): Listar Planes

## Changelog

* Se crea el endpoint usuario en el Microservicio Planes para obtener los planes asociados al usuario
* Se actualiza la coleccion de Postman del MS Planes

## Checklist

> Antes de solicitar reviews, los siguientes elementos deben estar listos

### Generales

- [X] La rama de origen sigue la convención mencionada en `.github/CONTRIBUTING`
- [X] Pull Request cuenta con un título apropiado
- [X] Se ha seleccionado el Milestone correspondiente
- [X] Se han colocado los labels para (microservicio, estado, tipo)

### CI/CD

- [ ] Se modificaron o agregaron pruebas al backlog
- [ ] Los cambios cuentan con la cobertura mínima de pruebas (70%)
- [X] Se actualizaron las colecciones de Postman
- [ ] Todos los checks del repositorio han sido exitosos

2024-04-11 18:47 UTC, s-cortes requested changes, later dismissed
1. Faltan pruebas unitarias para el GET
2. Te recomiendo mover los requests de postman arriba de las carpetas de "Fail scenarios"

2024-04-11 18:47 UTC, s-cortes commented on src/planes/presentation/api.py
> +    return jsonify(mapper.dto_to_external(query_result.result))
```suggestion
    return jsonify(mapper.dto_to_external(query_result.result))

```

2024-04-11 18:47 UTC, s-cortes commented on src/planes/application/exceptions.py
> +        super().__init__(HTTPStatus.UNPROCESSABLE_ENTITY.value, message, "user.not_asociated_to_plan")
```suggestion
        super().__init__(HTTPStatus.UNPROCESSABLE_ENTITY.value, message, "user.not_asociated_to_plan")

```

2024-04-11 18:47 UTC, s-cortes commented on src/planes/application/queries/get_planes_asociados_usuario.py
> +                raise UserNotAssociatedError(message="user.not_asociated_to_plan", code="usuario_plan_asociado.get.error.internal")
No entiendo esta condición

2024-04-11 18:47 UTC, s-cortes commented on src/planes/application/queries/get_planes_asociados_usuario.py
> +            return QueryResult(result=usuario_planes_asociados)
Falta el mapping de Entity a DTO

2024-04-14 15:55 UTC, mcastros05 approved these changes

2024-04-14 15:57 UTC, merged